# docker-compose.yml

version: '3'

volumes:
  pgdata:
  
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://myuser:mypassword@db:5432/mydb
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMAS: public
      PGRST_JWT_SECRET: 'rottengrapes.techisanopensourcecompany@438'

    depends_on:
      - db
  db:
    image: kartoza/postgis
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  # Uncomment this if you want to persist the data.
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    expose:
      - "8081"
    depends_on: 
      - server
      - db
    environment:
      API_URL: http://localhost:3000/